### ISSUE TITLE
Pewter Alloy bug

### ISSUE THREAD

**Issue by Sans1the1skeleton** [HopsandBarley/For-Science-#12]
In a quest of the metallurgy section there´s a bug, you can´t make the pewter alloys because you can´t make the mix correctly
for example: 87sn 10bi 3sb or any other of the mixes, it´s really anoying and I can´t play further than that point on the quest book

**Comment by HopsandBarley** [comment]
I just tested in and was able to get the 87-10-3 mix to work.  Are you using ingots or nuggets?

**Comment by Sans1the1skeleton** [comment]
Im using nuggets, it´s cheaper.
It works with ingots right?

**Comment by Sans1the1skeleton** [comment]
Ok, the recipe didn´t work for some reason, I managed to fix it.
For some reason CurseForge didn´t like my pc and decided to not download a file, this might be only a me problem so don´t worry, sorry for the inconvenience
