### ISSUE TITLE
I think the smithing table can´t be crafted

### ISSUE THREAD

**Issue by Sans1the1skeleton** [HopsandBarley/For-Science-#14]
I tried to craft the smithing table and instead of it the template table went up because the craft recipe is the same 2 iron cast alloy ingots and 4 of wood, I tried different types of wood and still nothing, I was lucky because I had a village nearby, but still you can´t craft it, could you please check it out?

**Comment by HopsandBarley** [comment]
I will take a look at it as soon as I get a chance. Thanks for letting me
know.

**Comment by HopsandBarley** [comment]
Just took a look at this, and you are correct, it's an issue.  It will be fixed in the next update.  Thanks for the tip.

**Comment by HopsandBarley** [comment]
The alloy template table recipe has been modified, allowing the smithing table to be crafted now.  Thanks for pointing out the error to me!

The update has been released on CurseForge.
