### ISSUE TITLE
Gold backpack craft recipe

### ISSUE THREAD

**Issue by Sans1the1skeleton** [HopsandBarley/For-Science-#15]
I find very strange that the craft for the golden back back has to be done with Blue gold instead of normal gold because all of the backpacks are made with the normal material, for example: iron backpack is made out of iron, diamond back is also made out of diamond, netherite backpack is made out of netherite, but the packback of gold is made out of blue gold, which is made out of gold and netherite, I think this doesn´t make much sense.

**Comment by HopsandBarley** [comment]
There are more recipes for blue gold than just the netherite one.  If you look at Blue Gold ingots, there are 2 recipes.  One for the induction furnace, and one for the alloy furnace.

I wanted the gold backpack to be something "more advanced" than the iron backpack.  With the way Rankine does mining, you get gold before you get iron, so it seemed silly to have gold be Tier 2 and iron be Tier 1. 

if you put 3 gold ingots and 1 iron ingot into an alloy furnace, it will make blue gold.

**Comment by Sans1the1skeleton** [comment]
never mind mi iq is minus 3
